config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "tasks", to: "tasks#index"

  get    "tasks/new",      to: "tasks#new"
  post   "tasks",          to: "tasks#create"

  get    "tasks/:id",      to: "tasks#show", as: :task

  get    "tasks/:id/edit", to: "tasks#edit", as: :edit
  patch  "tasks/:id",      to: "tasks#update"

  delete "tasks/:id",      to: "tasks#destroy", as: :delete

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  # before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)

    redirect_to tasks_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    # @task.update(params[:task])
    @task.update(task_params)

    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  # def set_task
  #   @tasks = Task.find(params[:id])
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sx-12 col-sm-6 col-md-4 col-md-offset-4">
      <h1>Edit Task</h1>
      <%= form_for(@task) do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title %>
        </div>
        <div class="form-group">

          <%= f.label :details %>
          <%= f.text_field :details %>
        </div>
        <div class="form-group">

          <%= f.label :completed %>
          <%= f.check_box :completed %>
        </div>

          <%= f.submit class: "btn btn-success" %>
      <% end %>

      <%= link_to "Go back to the list", tasks_path %>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sx-12 col-sm-6 col-md-4 col-md-offset-4">

      <h1>My Tasks</h1>
      <ul class="text-link">
        <% @tasks.each do |task| %>
          <li><%= link_to task.title, task_path(task) %></li>
          <!--   <#% if task.completed %>
            <#%= link_to task_path(task) do %>
              <i class="fas fa-check-circle"></i>
            <#% else %>
            <i class="fal fa-check-circle"></i>
             <#% end %>
          <#% end %> -->
        <% end %>
      </ul>
      <h4><%= link_to "New Task", tasks_new_path %></h4>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sx-12 col-sm-6 col-md-4 col-md-offset-4">
      <h1>New Task</h1>

        <%= form_for(@task) do |f| %>
          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title %>
          </div>
          <div class="form-group">

            <%= f.label :details %>
            <%= f.text_field :details %>
          </div>
          <div class="form-group">

            <%= f.label :completed %>
            <%= f.check_box :completed %>
          </div>

            <%= f.submit class: "btn btn-success" %>
        <% end %>

        <h4><%= link_to "Go back to the list", tasks_path %></h4>

    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sx-12 col-sm-6 col-md-4 col-md-offset-4">
      <h1><%= @task.title %></h1>
      <h5><%= @task.details %></h5>
      <p><%= @task.completed %></p>

      <%= link_to "Edit", edit_path(@task) %>
      <%= link_to "Delete", delete_path(@task), method: :delete, data: { confirm: "Are you sure?" } %>
      <%= link_to "Back Home", tasks_path %>
    </div>
  </div>
</div>